// <auto-generated />
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLayer.Orders.MaterialInformation", b =>
                {
                    b.Property<int>("MalzemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MalzemeID"));

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MalzemeKodu")
                        .HasColumnType("int");

                    b.HasKey("MalzemeID");

                    b.ToTable("MaterialInformations");
                });

            modelBuilder.Entity("BusinessLayer.Orders.OrderData", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"));

                    b.Property<int>("Agirlik")
                        .HasColumnType("int");

                    b.Property<int>("AgirlikBirim")
                        .HasColumnType("int");

                    b.Property<string>("CikisAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MalzemeKodu")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("MiktarBirim")
                        .HasColumnType("int");

                    b.Property<int>("MusteriSiparisNo")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarisAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiparisID");

                    b.ToTable("OrderDatas");
                });

            modelBuilder.Entity("BusinessLayer.Orders.OrderStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<bool>("DagitimMerkezinde")
                        .HasColumnType("bit");

                    b.Property<bool>("DagitimaCikti")
                        .HasColumnType("bit");

                    b.Property<bool>("SiparisAlindi")
                        .HasColumnType("bit");

                    b.Property<bool>("TeslimEdildi")
                        .HasColumnType("bit");

                    b.Property<bool>("TeslimEdilemedi")
                        .HasColumnType("bit");

                    b.Property<bool>("YolaCikti")
                        .HasColumnType("bit");

                    b.HasKey("StatusID");

                    b.ToTable("OrderStatuss");
                });
#pragma warning restore 612, 618
        }
    }
}
